### ISSUE TITLE
FeatureRequest: New Config-Field client_id to connect multiple home assistant instances to one bsh-box

### ISSUE THREAD

**Issue by glumanda** [tschamm/boschshc-hass#66] opened 2022-11-06 10:31 UTC
Please add a new config field in config_flow.py for using as arguments in function "create_credentials_and_validate". The new field is the input for the first and second (!) argument in function call "register" (result = helper.register(host, "HomeAssistant") at line 47. I checked this by hardcoding at my three ha instances (developement, integration and production) and it works.

The first argument in the register call is the key under which the bsh-box stores each particular connection (i gues). Using the box ip address stores all connections under one key and the last registration wins.

The second argument is the displayed name/text (surrounded by "oss_" and "_Binding") in the app for each connection.

Thx

PS: my python and ha skills not enough to extend by my self

**Comment by tschamm** [comment] 2023-01-29 10:46
Closing this as it is a duplicate of #64

**Closed by tschamm** 2023-01-29 10:46 UTC
Labels: duplicate
