### ISSUE TITLE
Thermostats showing 0 degree after update

### ISSUE THREAD

**Issue by erd82** [tschamm/boschshc-hass#63] opened 2022-10-06 12:50 UTC
After installing the [latest October update](https://www.bosch-smarthome.com/de/de/service/aktuelle-meldungen/release-infos/system-solutions/2022-10-05.html), some of the thermostats (HT II) only show 0°C in Home Assistant.

![image](https://user-images.githubusercontent.com/63564291/194314108-a6e12674-3440-42be-8af9-ebbae895a523.png)

![image](https://user-images.githubusercontent.com/63564291/194314160-3065a056-062f-4883-a40f-36c8ad994d95.png)

Here you can find the current Home Assistant logs for Bosch: https://www.dropbox.com/s/k71gqkhivjd92lv/20221006-halogsbosch.zip?dl=0

Any idea how to fix this?

Cheers, erd

**Comment by erd82** [comment] 2022-10-06 19:14
Due to any reason we had a short blackout of around 2 seconds which caused (1) a reboot of my Home Assistant installation and (2) a reboot of the Bosch Smart Home Controller. After that the temperature is correctly transferred to Home Assistant again.

![image](https://user-images.githubusercontent.com/63564291/194399218-c1a2f8fb-e4a6-48f4-80b3-9323a119719b.png)

Finally there could be two reasons that fixed the issue:
* Reload of Bosch integration (caused by HA restart)
* Restart of Bosch Smart Home Controller

If someone else notices this issue after updating Bosch Smart Home Controller, please try the options above one by one and report here, what helped to fix the issue.

**Comment by nikolozka** [comment] 2022-10-29 22:08
Just set up my new bosch kit today and i'm seeing a similar problem. seemingly triggered by changing the valve temperature, but not really 100% surethat's really the trigger. 

Valvetappet entity doesn't see to be affected.

Restarting the HA instance doesn't seem to help. I tried resetting the Bosch Controller once and it seemed to resolve the problem, but it takes quite a bit of time for it to come back online after a restart.

Resetting the thermostats themselves also seems to solve the issue (reseat the batteries)

Not sure if the problem is on HA end or on Bosch end as the temperature reading also disappears from Bosch app.

Before starting to report 0 degrees the devices will flip back and forth between being unavailable a couple of times sometimes it will take a while for them to start posting again.

Can't confirm if this has anything to do with the Bosch Controller update as I didn't get to use them at all before the update.
I might use the official Bosch integration for now if this problem persists, since my current automations don't realy on writing the temperature to thermostats, I just use their Valve readings to controll the boiler at the moment.

Let me know if I should attach logs if someone wants to do a deeper dive on those.

**Comment by tschamm** [comment] 2023-01-30 21:57
Close it for now, please reopen if problem persists.

**Closed by tschamm** 2023-01-30 21:57 UTC
