### ISSUE TITLE
Use new entity type Valve

### ISSUE THREAD

**Issue by hardysim** [tschamm/boschshc-hass#142] opened 2024-01-05 11:34 UTC
In the newest version of HA a new **valve** entity type is available which seems fitting for the **Valvetappet** entity of the bosch thermostats.

https://www.home-assistant.io/blog/2024/01/03/release-20241/#new-entity-type-valve

Most of the time one would want to use the thermostat card but to show the current status of the valve the new card looks great. Maybe we can use both?

![image](https://github.com/tschamm/boschshc-hass/assets/3737512/7bb3671c-0366-49d8-abd9-44b94bc37a41)

**Comment by tschamm** [comment] 2024-01-06 11:16
Implemented in https://github.com/tschamm/boschshc-hass/commit/0e7cf3ffa4740e642e1a7247ca3098ab6e804732
Open/Closing of valve is not possible, as the valve tappet service is only reporting the position of the valve, not allowing to control the valve directly. So the implementation is more a duplicate of the valve sensor entity.

**Closed by tschamm** 2024-01-06 11:16 UTC

**Comment by hardysim** [comment] 2024-01-09 12:42
Thx!
There is a new tag for https://github.com/tschamm/boschshc-hass/releases/tag/0.4.79 but no release? I cannot see the new version in HACS.

**Comment by soxhi8** [comment] 2024-01-18 03:11
The current implementation breaks compatibility on prior versions of Home Assistant. On my 2023.12.3-instance it results in an AttributeError:
`  File "/config/custom_components/bosch_shc/__init__.py", line 56, in <module>
    Platform.VALVE,
    ^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/enum.py", line 784, in __getattr__
    raise AttributeError(name) from None
AttributeError: VALVE`

Rolled back to 0.4.78 for now, since I am trying to stay away from the bleeding edge updates that Home Assistant itself sometimes releases.
